services:
  server:
    build: foodplanner-server
    restart: unless-stopped
    env_file:
      - project.env
    volumes:
      - ./foodplanner-server:/app
    ports:
      - 8000:8080
    depends_on:
      - database

  client:
    build: client
    restart: unless-stopped
    volumes:
      - ./client:/app
    ports:
      - 4321:4321
    depends_on:
      - server
  
  database:
    container_name: foodplanner_postgresql_database
    image: postgres:17.0
    restart: unless-stopped
    env_file:
      - project.env
    volumes:
      - db-data:/var/lib/postgresql/data

  database-migrations:
    image: flyway/flyway:11.10
    env_file:
      - project.env
    depends_on:
      - database
    volumes:
      - ./database-migrations:/flyway/db/migration
    command: -connectRetries=60 -baselineOnMigrate=true migrate

volumes:
  db-data:
    